language: node_js

node_js:
  - node

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - npm test

after_success:
  - npm run coveralls
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info
